# Generated by Django 3.0 on 2022-06-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sudoku_image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
