# Generated by Django 3.0 on 2022-06-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_image_sudoku_image_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sudoku_image_result',
            field=models.ImageField(blank=True, null=True, upload_to='result/'),
        ),
    ]
